// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "processing/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountsUsecase is an autogenerated mock type for the AccountsUsecase type
type AccountsUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, acc, ip
func (_m *AccountsUsecase) Create(ctx context.Context, acc *domain.Account, ip string) error {
	ret := _m.Called(ctx, acc, ip)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account, string) error); ok {
		r0 = rf(ctx, acc, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *AccountsUsecase) GetAccount(ctx context.Context, id uuid.UUID) (*domain.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionHistory provides a mock function with given fields: ctx, accountID, limit, offset
func (_m *AccountsUsecase) TransactionHistory(ctx context.Context, accountID uuid.UUID, limit int, offset int) (int, []domain.Transaction, error) {
	ret := _m.Called(ctx, accountID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for TransactionHistory")
	}

	var r0 int
	var r1 []domain.Transaction
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (int, []domain.Transaction, error)); ok {
		return rf(ctx, accountID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) int); ok {
		r0 = rf(ctx, accountID, limit, offset)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) []domain.Transaction); ok {
		r1 = rf(ctx, accountID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, accountID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAccountsUsecase creates a new instance of AccountsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsUsecase {
	mock := &AccountsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
