// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "processing/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, email, password, ip
func (_m *AuthUseCase) Login(ctx context.Context, email string, password string, ip string) (*domain.TokenPair, error) {
	ret := _m.Called(ctx, email, password, ip)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.TokenPair, error)); ok {
		return rf(ctx, email, password, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.TokenPair); ok {
		r0 = rf(ctx, email, password, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken, ip
func (_m *AuthUseCase) Logout(ctx context.Context, refreshToken string, ip string) error {
	ret := _m.Called(ctx, refreshToken, ip)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, refreshToken, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogoutAll provides a mock function with given fields: ctx, userID
func (_m *AuthUseCase) LogoutAll(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Refresh provides a mock function with given fields: ctx, refreshToken, ip
func (_m *AuthUseCase) Refresh(ctx context.Context, refreshToken string, ip string) (*domain.TokenPair, error) {
	ret := _m.Called(ctx, refreshToken, ip)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *domain.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.TokenPair, error)); ok {
		return rf(ctx, refreshToken, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.TokenPair); ok {
		r0 = rf(ctx, refreshToken, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, refreshToken, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, email, password, name, ip
func (_m *AuthUseCase) Register(ctx context.Context, email string, password string, name string, ip string) (*domain.Account, error) {
	ret := _m.Called(ctx, email, password, name, ip)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.Account, error)); ok {
		return rf(ctx, email, password, name, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.Account); ok {
		r0 = rf(ctx, email, password, name, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, password, name, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
