// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	decimal "processing/internal/decimal"
	domain "processing/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// GetTransaction provides a mock function with given fields: ctx, transactionID, userID, key
func (_m *TransactionUsecase) GetTransaction(ctx context.Context, transactionID uuid.UUID, userID uuid.UUID, key string) (domain.Transaction, error) {
	ret := _m.Called(ctx, transactionID, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (domain.Transaction, error)); ok {
		return rf(ctx, transactionID, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) domain.Transaction); ok {
		r0 = rf(ctx, transactionID, userID, key)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, transactionID, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionFilter provides a mock function with given fields: ctx, t, userID, key
func (_m *TransactionUsecase) GetTransactionFilter(ctx context.Context, t *domain.TransactionFilter, userID uuid.UUID, key string) ([]domain.Transaction, error) {
	ret := _m.Called(ctx, t, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionFilter")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionFilter, uuid.UUID, string) ([]domain.Transaction, error)); ok {
		return rf(ctx, t, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransactionFilter, uuid.UUID, string) []domain.Transaction); ok {
		r0 = rf(ctx, t, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TransactionFilter, uuid.UUID, string) error); ok {
		r1 = rf(ctx, t, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: ctx, sender_id, receiver_id, key, amount
func (_m *TransactionUsecase) Transfer(ctx context.Context, sender_id uuid.UUID, receiver_id uuid.UUID, key string, amount decimal.Decimal) (string, error) {
	ret := _m.Called(ctx, sender_id, receiver_id, key, amount)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, decimal.Decimal) (string, error)); ok {
		return rf(ctx, sender_id, receiver_id, key, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, decimal.Decimal) string); ok {
		r0 = rf(ctx, sender_id, receiver_id, key, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, sender_id, receiver_id, key, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionUsecase creates a new instance of TransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionUsecase {
	mock := &TransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
