name: Check
on: push
jobs: 
  golangci-lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: install deps
        run: go mod download
      - name: Lint
        run: go vet ./...
  test:
    needs: [golangci-lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25', '1.26']
        os: ['ubuntu-latest', 'windows-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: install deps
        run: go mod download
      - name: Run tests
        run: go test -coverprofile=coverage.out ./...
      - name: Check coverage threshold
        run: |
            COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
            echo "Coverage: $COVERAGE%"
            if (( $(echo "$COVERAGE < 50" | bc -l) )); then
              echo "Coverage is below 50%"
              exit 1
            fi