name: Check
on: push
jobs: 
  golangci-lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v7
      - name: install deps
        run: go mod download
      - name: Lint
        run: go vet ./...
  test:
    needs: [golangci-lint]
    runs-on: ubuntu latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: install deps
        run: go mod download
      - name: test
        run: go tool cover -func=coverage | grep total